FROM node:20-slim

WORKDIR /app

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy and install deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .


# Expose Vite dev port
EXPOSE 5173

# Start dev server with hot reload
CMD ["pnpm", "dev", "--host"]