services:
  db:
    image: postgres:15
    container_name: inventory_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: inventory_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:
