services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    command: pnpm dev --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: inventory_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    command: pnpm start:dev
    container_name: inventory_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules

volumes:
  pgdata:
  node_modules_backend:
  node_modules_frontend: